version: '3'

services:
    web:
        working_dir: /project
        image: nginx
        container_name: payment_nginx
        volumes:
            - .:/project
            - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "81:80"
            - "443:443"
        restart: always
        depends_on:
            - php

    php:
        working_dir: /project
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        restart: always
        container_name: payment_php
        expose:
            - "9000"
        volumes:
            - .:/project
            - ./conf/php:/usr/local/etc:ro

    db:
        image: mysql:5.7
        container_name: cms_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: lat_cms
            MYSQL_USER: mylat
            MYSQL_PASSWORD: lat123!@#
        ports:
        - 3306:3306
        volumes:
        - ./docker/data:/var/lib/mysql

    adminer:
        image: clue/adminer
        container_name: adminer
        restart: always
        ports:
        - "8060:80"

#networks:
#    default:
#      external:
#        name: bao_project

